### ISSUE TITLE
difficult to use for specific region

### ISSUE THREAD

**Issue by halderm100** [jfaghm/OceanEddies#3]
I want to use this tools for my area of interest say Bay of Bengal. I didn't understand how it is possible. Please help.

**Comment by lematt1991** [comment]
You want to run the algorithm or you want to use the resulting data for your area of interest?  We've already run the detection algorithm for the entire globe.  You can find the results [here](climatechange.cs.umn.edu/eddies/eddies_data.html
).

**Comment by halderm100** [comment]
I want to run the algorithm for Bay of Bengal (75E-100E;4N-24N). I have monthly mean SSHA data (1/4 degree resolution) from January 2006 - December 2015.

**Comment by lematt1991** [comment]
OK, can you be more specific about the issues that you are having?  As long as you have a three-dimensional matrix of SSHA data (lat x lon x date), and the lat/lon arrays to go with it, you should be able to do exactly what is described in the [README](https://github.com/jfaghm/OceanEddies/blob/master/README.md#usage).
